

COLLECTION_LIST = ['4D-Lung',
 'A091105',
 'ACNS0332',
 'ACRIN-6698',
 'ACRIN-Contralateral-Breast-MR',
 'ACRIN-FLT-Breast',
 'ACRIN-HNSCC-FDG-PET-CT',
 'ACRIN-NSCLC-FDG-PET',
 'AHEP0731',
 'AHOD0831',
 'ARAR0331',
 'AREN0532',
 'AREN0533',
 'AREN0534',
 'Adrenal-ACC-Ki67-Seg',
 'Advanced-MRI-Breast-Lesions',
 'Anti-PD-1_Lung',
 'B-mode-and-CEUS-Liver',
 'BREAST-DIAGNOSIS',
 'Breast-Cancer-Screening-DBT',
 'Breast-MRI-NACT-Pilot',
 'C4KC-KiTS',
 'CALGB50303',
 'CBIS-DDSM',
 'CC-Radiomics-Phantom',
 'CC-Radiomics-Phantom-2',
 'CC-Radiomics-Phantom-3',
 'CC-Tumor-Heterogeneity',
 'CMB-AML',
 'CMB-BRCA',
 'CMB-CRC',
 'CMB-GEC',
 'CMB-LCA',
 'CMB-MEL',
 'CMB-MML',
 'CMB-OV',
 'CMB-PCA',
 'CMMD',
 'COVID-19-AR',
 'COVID-19-NY-SBU',
 'CPTAC-AML',
 'CPTAC-CCRCC',
 'CPTAC-CM',
 'CPTAC-LSCC',
 'CPTAC-LUAD',
 'CPTAC-PDA',
 'CPTAC-SAR',
 'CPTAC-UCEC',
 'CT COLONOGRAPHY',
 'CT Lymph Nodes',
 'CT-Phantom4Radiomics',
 'CT-vs-PET-Ventilation-Imaging',
 'CT4Harmonization-Multicentric',
 'CTpred-Sunitinib-panNET',
 'Colorectal-Liver-Metastases',
 'DRO-Toolkit',
 'Duke-Breast-Cancer-MRI',
 'EA1141',
 'GBM-DSC-MRI-DRO',
 'HCC-TACE-Seg',
 'ICDC-Glioma',
 'ISPY1',
 'ISPY2',
 'LCTSC',
 'LDCT-and-Projection-data',
 'LIDC-IDRI',
 'Lung Phantom',
 'Lung-Fused-CT-Pathology',
 'Lung-PET-CT-Dx',
 'LungCT-Diagnosis',
 'MIDI-B-Curated-Test',
 'MIDI-B-Curated-Validation',
 'MIDI-B-Synthetic-Test',
 'MIDI-B-Synthetic-Validation',
 'MIDRC-RICORD-1A',
 'MIDRC-RICORD-1B',
 'MIDRC-RICORD-1C',
 'MRI-DIR',
 'Mediastinal-Lymph-Node-SEG',
 'Mouse-Astrocytoma',
 'Mouse-Mammary',
 'NSCLC Radiogenomics',
 'NSCLC-Radiomics',
 'NSCLC-Radiomics-Genomics',
 'NSCLC-Radiomics-Interobserver1',
 'NaF PROSTATE',
 'PDMR-292921-168-R',
 'PDMR-425362-245-T',
 'PDMR-521955-158-R4',
 'PDMR-833975-119-R',
 'PDMR-997537-175-T',
 'PDMR-BL0293-F563',
 'PDMR-Texture-Analysis',
 'PROSTATE-DIAGNOSIS',
 'PROSTATE-MRI',
 'PROSTATEx',
 'Pancreas-CT',
 'Pancreatic-CT-CBCT-SEG',
 'Pediatric-CT-SEG',
 'Pelvic-Reference-Data',
 'Phantom FDA',
 'Prostate Fused-MRI-Pathology',
 'Prostate-3T',
 'Prostate-Anatomical-Edge-Cases',
 'Prostate-MRI-US-Biopsy',
 'Pseudo-PHI-DICOM-Data',
 'QIBA CT-1C',
 'QIBA-CT-Liver-Phantom',
 'QIN Breast DCE-MRI',
 'QIN LUNG CT',
 'QIN PET Phantom',
 'QIN-BREAST',
 'QIN-BREAST-02',
 'QIN-PROSTATE-Repeatability',
 'RIDER Breast MRI',
 'RIDER Lung CT',
 'RIDER Lung PET-CT',
 'RIDER PHANTOM MRI',
 'RIDER PHANTOM PET-CT',
 'RIDER Pilot',
 'ReMIND',
 'S0819',
 'SPIE-AAPM Lung CT Challenge',
 'Soft-tissue-Sarcoma',
 'Spine-Mets-CT-SEG',
 'StageII-Colorectal-CT',
 'TCGA-BLCA',
 'TCGA-BRCA',
 'TCGA-CESC',
 'TCGA-COAD',
 'TCGA-ESCA',
 'TCGA-KICH',
 'TCGA-KIRC',
 'TCGA-KIRP',
 'TCGA-LIHC',
 'TCGA-LUAD',
 'TCGA-LUSC',
 'TCGA-OV',
 'TCGA-PRAD',
 'TCGA-READ',
 'TCGA-SARC',
 'TCGA-STAD',
 'TCGA-THCA',
 'TCGA-UCEC',
 'UPENN-GBM',
 'VAREPOP-APOLLO',
 'VICTRE',
 'Vestibular-Schwannoma-MC-RC',
 'Vestibular-Schwannoma-SEG']